// AUTO-GENERATED BY CHATGPT – Enhanced theme pack with realistic backgrounds
export interface ThemeDef {
  id: string;
  label: string;
  colors: {
    bg: string;       // app/panel outer bg
    panel: string;    // inner card bg (can be semi-transparent)
    header: string;   // header bg (gradient ok)
    text: string;     // text color
    accent: string;   // primary accent
    border: string;   // border color
    input: string;    // input bg
  };
  backgroundImage?: string; // e.g. url('/themes/xxx.jpg')
}

export const themeDefs: ThemeDef[] = [
  // ——— CORE ———
  {
    id: "minimal",
    label: "Minimal",
    colors: {
      bg: "#f9f9f9",
      panel: "rgba(255,255,255,0.85)",
      header: "linear-gradient(90deg,#e0e0e0,#f9f9f9)",
      text: "#111111",
      accent: "#444444",
      border: "rgba(0,0,0,0.1)",
      input: "rgba(255,255,255,0.95)"
    },
    backgroundImage: "url('/themes/minimal.jpg')"
  },
  {
    id: "gothic",
    label: "Gothic",
    colors: {
      bg: "#0a0a0a",
      panel: "rgba(20,20,20,0.85)",
      header: "linear-gradient(90deg,#111111,#1c1c1c)",
      text: "#f5f5f5",
      accent: "#8b0000",
      border: "rgba(255,255,255,0.15)",
      input: "rgba(10,10,10,0.7)"
    },
    backgroundImage: "url('/themes/gothic.jpg')"
  },
  {
    id: "neonokyanus",
    label: "Neon Okyanus",
    colors: {
      bg: "#00111a",
      panel: "rgba(255,255,255,0.06)",
      header: "linear-gradient(90deg,#00d4ff,#0066ff)",
      text: "#e6fbff",
      accent: "#00d4ff",
      border: "rgba(0,212,255,0.30)",
      input: "rgba(0,0,0,0.35)"
    },
    backgroundImage: "url('/themes/neon-waves.jpg')"
  },

  // ——— FUN / MOVIES / HEROES ———
  {
    id: "mcqueen",
    label: "Şimşek McQueen",
    colors: {
      bg: "#ff0000",
      panel: "rgba(255,255,255,0.08)",
      header: "linear-gradient(90deg,#ff0000,#ff8800)",
      text: "#fff5f5",
      accent: "#ffd700",
      border: "rgba(255,255,255,0.25)",
      input: "rgba(0,0,0,0.4)"
    },
    backgroundImage: "url('/themes/mcqueen.jpg')"
  },
  {
    id: "batman",
    label: "Batman",
    colors: {
      bg: "#000000",
      panel: "rgba(20,20,24,0.55)",
      header: "linear-gradient(90deg,#0f0f14,#1a1a22)",
      text: "#f5f5f5",
      accent: "#ffd700",
      border: "rgba(255,215,0,0.25)",
      input: "rgba(12,12,16,0.6)"
    },
    backgroundImage: "url('/themes/batman-gotham.jpg')"
  },
  {
    id: "spiderman",
    label: "Spiderman",
    colors: {
      bg: "#120010",
      panel: "rgba(255,255,255,0.06)",
      header: "linear-gradient(90deg,#7a001e,#001e7a)",
      text: "#ffebf0",
      accent: "#ff2040",
      border: "rgba(255,32,64,0.28)",
      input: "rgba(0,0,0,0.35)"
    },
    backgroundImage: "url('/themes/spiderman-web.jpg')"
  },
  {
    id: "superman",
    label: "Superman",
    colors: {
      bg: "#0e1a58",
      panel: "rgba(255,255,255,0.08)",
      header: "linear-gradient(90deg,#0e1a58,#3b82f6,#facc15)",
      text: "#eaf2ff",
      accent: "#facc15",
      border: "rgba(250,204,21,0.25)",
      input: "rgba(10,20,60,0.45)"
    },
    backgroundImage: "url('/themes/superman-sky.jpg')"
  },
  {
    id: "joker",
    label: "Joker",
    colors: {
      bg: "#0f0016",
      panel: "rgba(255,255,255,0.06)",
      header: "linear-gradient(90deg,#4b0082,#008f5a)",
      text: "#f5e9ff",
      accent: "#22c55e",
      border: "rgba(125,211,252,0.25)",
      input: "rgba(0,0,0,0.35)"
    },
    backgroundImage: "url('/themes/joker-chaos.jpg')"
  },
  {
    id: "constantine",
    label: "John Constantine",
    colors: {
      bg: "#0d0d0e",
      panel: "rgba(255,255,255,0.07)",
      header: "linear-gradient(90deg,#1b1b1b,#403618)",
      text: "#f9f7ec",
      accent: "#f2c66d",
      border: "rgba(242,198,109,0.28)",
      input: "rgba(10,10,10,0.45)"
    },
    backgroundImage: "url('/themes/constantine-occult.jpg')"
  },
  {
    id: "vader",
    label: "Darth Vader / Anakin",
    colors: {
      bg: "#000000",
      panel: "rgba(255,255,255,0.06)",
      header: "linear-gradient(90deg,#1a0000,#4d0000)",
      text: "#f8eaea",
      accent: "#ef4444",
      border: "rgba(239,68,68,0.3)",
      input: "rgba(0,0,0,0.4)"
    },
    backgroundImage: "url('/themes/darthvader.jpg')"
  },

  // ——— CUTE ———
  {
    id: "hellokitty",
    label: "Hello Kitty",
    colors: {
      bg: "#fde1eb",
      panel: "rgba(255,255,255,0.78)",
      header: "linear-gradient(90deg,#ff8fb3,#ffd1e0)",
      text: "#4a1724",
      accent: "#ff5c8a",
      border: "rgba(255,140,179,0.35)",
      input: "rgba(255,255,255,0.92)"
    },
    backgroundImage: "url('/themes/hellokitty.jpg')"
  },
  {
    id: "mylittlepony",
    label: "My Little Pony",
    colors: {
      bg: "#fff0fa",
      panel: "rgba(255,255,255,0.80)",
      header: "linear-gradient(90deg,#ffb3e6,#c3e7ff,#e6ffe6,#ffe5b3)",
      text: "#401a2b",
      accent: "#ff80d5",
      border: "rgba(255,179,230,0.35)",
      input: "rgba(255,255,255,0.92)"
    },
    backgroundImage: "url('/themes/mylittlepony.jpg')"
  },

  // ——— MINECRAFT ———
  {
    id: "minecraft-flowers",
    label: "Minecraft Çiçekler",
    colors: {
      bg: "#1f3a1f",
      panel: "rgba(255,255,255,0.07)",
      header: "linear-gradient(90deg,#4caf50,#2e7d32)",
      text: "#e5fbe6",
      accent: "#81c784",
      border: "rgba(129,199,132,0.3)",
      input: "rgba(0,0,0,0.35)"
    },
    backgroundImage: "url('/themes/minecraft-flowers.jpg')"
  },
  {
    id: "macera",
    label: "Minecraft Macera / Madencilik",
    colors: {
      bg: "#1a1a1a",
      panel: "rgba(255,255,255,0.07)",
      header: "linear-gradient(90deg,#1f2937,#111827)",
      text: "#e5e7eb",
      accent: "#cbd5e1",
      border: "rgba(148,163,184,0.25)",
      input: "rgba(0,0,0,0.35)"
    },
    backgroundImage: "url('/themes/minecraft-mining.jpg')"
  },
  {
    id: "nether",
    label: "Minecraft Nether",
    colors: {
      bg: "#1a0000",
      panel: "rgba(255,255,255,0.06)",
      header: "linear-gradient(90deg,#7a001e,#ff3300,#ff8200)",
      text: "#ffe9e6",
      accent: "#ff6b00",
      border: "rgba(255,69,0,0.28)",
      input: "rgba(0,0,0,0.35)"
    },
    backgroundImage: "url('/themes/minecraft-nether.jpg')"
  },
  {
    id: "end",
    label: "Minecraft End",
    colors: {
      bg: "#0b0011",
      panel: "rgba(255,255,255,0.06)",
      header: "linear-gradient(90deg,#4b0082,#800080)",
      text: "#efe6ff",
      accent: "#a855f7",
      border: "rgba(168,85,247,0.28)",
      input: "rgba(0,0,0,0.35)"
    },
    backgroundImage: "url('/themes/minecraft-end.jpg')"
  },
];

export const themeMap: Record<string, ThemeDef> = Object.fromEntries(
  themeDefs.map(t => [t.id, t])
);

export function getTheme(id?: string): ThemeDef {
  if (!id) return themeMap["minimal"] || themeDefs[0];
  return themeMap[id] || themeMap["minimal"] || themeDefs[0];
}

// For selects: value/label pairs
export const themes = themeDefs.map(t => ({ value: t.id, label: t.label }));
