name: Weekly Firestore Reset

on:
  schedule:
    - cron: "5 0 * * 1"  # Pazartesi 00:05 UTC
  workflow_dispatch:

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm install firebase-admin

      - name: Run reset script
        run: node scripts/weeklyReset.js
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
